name: Playwright and vitest Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    - name: Set environment variables
      run: |
        export SECRET_PG_HOST="${{ secrets.SECRET_PG_HOST }}"
        export DEV="${{ secrets.DEV }}"

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run e2e tests
      run: |
        echo "SECRET_PG_HOST is $SECRET_PG_HOST"
        echo "DEV is $DEV"
        npm run test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
